
server:
  port: 8083


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092

    #   Custom defined values
    custom:
      candidate-topic: job-events
      application_topic: application_topic
      job_topic: job_topic

  application:
    name: job-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/${MONGODB_NAME:job-db}
      #      authentication-database: admin
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      database: ${MONGODB_DB_NAME:job-db}
      port: 27017
      host: localhost

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}