server:
  port: 8083


spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    #   Custom defined values
    custom:
      candidate-topic: ${KAFKA_CANDIDATE_TOPIC:candidate-events}
      application_topic: ${KAFKA_APPLICATION_TOPIC:application-events}
      job_topic: ${KAFKA_JOB_TOPIC:job-events}

  application:
    name: ${APPLICATION_NAME:job-service}
  data:
    mongodb:
      username: ${MONGO_USERNAME:mongo}
      password: ${MONGO_PASSWORD:mongo}
      database: ${MONGO_DATABASE:job-db}
      port: 27017
      host: ${MONGO_URL:localhost}
      auto-index-creation: true

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}