server:
  port: 8087

spring:

  # Kafka Config
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: services-group
    custom:
      enable-listeners: true # Set this false, to disable all kafka Listeners
      notification-topic: notification-events

  # Mail config
  mail:
    host: smtp.gmail.com
    username: sanjayakoju42@gmail.com
    password: fxahxqzfghwliack
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

    #  mail:
    #    password: fxahxqzfghwliack
    #    username: sanjayakoju42@gmail.com
    #    host: smtp.gmail.com
    #    port: '587'
    ##    protocol: smtp
    #    properties:
    #      mail:
    #        smtp:
    #          auth: 'true'
    #          starttls:
    #            enable: 'true'
    #          connection-timeout: '5000'
    #          write timeout: '5000'

  # Mail Config
  #  mail:
  #    properties:
  #      mail:
  #        smtp:
  #          starttls:
  #            enable: 'true'
  #          timeout: '5000'
  #          auth: 'true'
  #          connectiontimeout: '5000'
  #          writetimeout: '5000'
  #          ssl:
  #            trust: host
  #    host: smtp.gmail.com
  #    username: sanjayakoju42@gmail.com
  #    password: fxahxqzfghwliack
  #    port: '587'

support:
  test:
    email: testmailswa@gmail.com
    password: sanjaya77


