
server:
  port: 8085

spring:
  application:
    name: application-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    application_topic: ${KAFKA_APPLICATION_TOPIC:application-events}
    job_topic: ${KAFKA_JOB_TOPIC:job-events}

  data:
    mongodb:
#      uri: mongodb://localhost:27017/${MYSQL_DB_NAME:application-db}
      #      authentication-database: admin
      username: ${MONGO_USERNAME:mongo}
      password: ${MONGO_PASSWORD:mongo}
      database: ${MONGO_DATABASE:application-db}
      port: 27017
      host: ${MONGO_URL:localhost}
      auto-index-creation: true

  # Sleuth and Zipkin Config (Used for distributed tracing and logs)
  sleuth:
    sampler:
      percentage: 1 # 1 Indicate Sleuth send 100 percent log to the zipkin (by default for performance issue spring sleuth send 10 percent log to zipkin in enterprise)
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    baseUrl: ${ZIPKIN_URL:http://localhost:9411/}

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}

#  data:
#    mongodb:
#      host: localhost
#      uri: mongodb://localhost:27017/${MYSQL_DB_NAME:application-db}
#      port: 27017
#      database: application-db
#      username: root
#      password: example

#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.auto-index-creation=true


#app:
#  url:
#    job: ${JOB_URL:localhost:8081}
