
server:
  port: 8085

spring:
  application:
    name: application-service

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:services-group}

    #   Custom defined values
    custom:
      candidate-topic: ${KAFKA_CANDIDATE_TOPIC:candidate-events}
      application-topic: ${KAFKA_APPLICATION_TOPIC:application-events}
      job-topic: ${KAFKA_JOB_TOPIC:job-events}
      notification-topic: ${KAFKA_NOTIFICATION_TOPIC:notification-events}

  data:
    mongodb:
      #      uri: mongodb://${MONGO_URL:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:candidate-db}
      #      authentication-database: admin
      username: ${MONGO_USERNAME:mongo}
      password: ${MONGO_PASSWORD:mongo}
      database: ${MONGO_DATABASE:application-db}
      port: 27017
      host: ${MONGO_URL:localhost}
      auto-index-creation: true

  # Sleuth and Zipkin Config (Used for distributed tracing and logs)
  sleuth:
    sampler:
      percentage: 1 # 1 Indicate Sleuth send 100 percent log to the zipkin (by default for performance issue spring sleuth send 10 percent log to zipkin in enterprise)
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    baseUrl: ${ZIPKIN_URL:http://localhost:9411/}

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}
