version: '3.9'

services:

  cassandra:
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra_data: {}


