server:
  port: 8082


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092

    #   Custom defined values
    custom:
      candidate-topic: candidate-events

  application:
    name: candidate-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/${MYSQL_DB_NAME:candidate-db}
#      authentication-database: admin
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      database: ${MONGODB_DB_NAME:candidate-db}
      port: 27017
      host: localhost

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}