server:
  port: 8082


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092

    #   Custom defined values
    custom:
      candidate-topic: candidate-events

  application:
    name: candidate-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/${MONGO_INITDB_DATABASE:candidate-db}
      authentication-database: admin
#      username: ${MONGO_INITDB_ROOT_USERNAME:root}
#      password: ${MONGO_INITDB_ROOT_PASSWORD:pswd}
      database: ${MONGO_INITDB_DATABASE:candidate-db}
      port: 27017
      host: localhost
      auto-index-creation: true

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}