server:
  port: 8082


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092

    #   Custom defined values
    custom:
      candidate-topic: candidate-events
      notification-topic: notification-events

  # Service Name
  application:
    name: candidate-service

  # Mongo DB Config
  data:
    mongodb:
      uri: mongodb://localhost:27017/${MONGO_INITDB_DATABASE:candidate-db}
      authentication-database: admin
#      username: ${MONGO_INITDB_ROOT_USERNAME:root}
#      password: ${MONGO_INITDB_ROOT_PASSWORD:pswd}
      database: ${MONGO_INITDB_DATABASE:candidate-db}
      port: 27017
      host: localhost
      auto-index-creation: true

  # Sleuth and Zipkin Config (Used for distributed tracing and logs)
  sleuth:
    sampler:
      percentage: 1 # 1 Indicate Sleuth send 100 percent log to the zipkin (by default for performance issue spring sleuth send 10 percent log to zipkin in enterprise)
  zipkin:
    baseUrl: http://localhost:9411/

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:swa-proj1-jwt-secret}