version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: