version: '3.9'

services:

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
#      - ES_JAVA_OPTS="-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ports:
      - 9200:9200
