apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-app
  ports:
    - port: 80
      nodePort: 30070 # exposing to local, to access this service
      targetPort: 8070
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: proj3_auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            # Database: MySQL
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: mysql_url
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: mysql_authDBName
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: mysql_pass

            # App Specific
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: jwt-secret-key