apiVersion: v1
kind: Service
metadata:
  name: candidate-service
spec:
  selector:
    app: candidate-service
  ports:
    - port: 80
      nodePort: 30082
      targetPort: 8082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-service
  template:
    metadata:
      labels:
        app: candidate-service
    spec:
      containers:
        - name: candidate-service
          image: proj3_candidate-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            # PROFILE
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            # Database: MongoDB
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: mongo_url
            - name: MONGO_DATABASE
              valueFrom:
                name: core-configs
                key: mongo_candidateDBName
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: mongo_user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: mongo_pass

            # App Specific
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: jwt-secret-key

