apiVersion: v1
kind: Service
metadata:
  name: candidate-service
spec:
  selector:
    app: candidate-service
  ports:
    - port: 80
      nodePort: 30082
      targetPort: 8082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-service
  template:
    metadata:
      labels:
        app: candidate-service
    spec:
      containers:
        - name: candidate-service
          image: proj3_candidate-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MONGO_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: database-configs
                  key: candidate_mongodbURL

            - name: MONGO_INITDB_DATABASE
              valueFrom:
                name: database-configs
                key: candidate_dbName
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo_pass
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key

