apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
type: Opaque
data:
  # Database  # user pass, root
  mysql_user: cm9vdAo=
  mysql_pass: cm9vdAo=

  # user pass, mongo
  mongo_user: bW9uZ28=
  mongo_pass: bW9uZ28=

  # user pass, elastic
  elastic_username: ZWxhc3RpYwo=
  elastic_password: ZWxhc3RpYwo=

  # redis pass, redis
  redis_password: cmVkaXM=

  # App Specific
  # swa-proj3-jwt-secret
  jwt-secret-key: c3dhLXByb2ozLWp3dC1zZWNyZXQK
